---

- name: Add GPG key
  rpm_key: 
    key: https://packages.treasuredata.com/GPG-KEY-td-agent

- name: Add official repository
  yum_repository:
    name: TreasureData
    description: TreasureData YUM repo
    file: td
    baseurl: http://packages.treasuredata.com/3/redhat/$releasever/$basearch
    gpgcheck: yes

- name: Install td-agent
  yum: 
    name: "td-agent-{{ fluentd_version }}"
    enablerepo: TreasureData
    update_cache: yes  

- name: Ensure td-agent is started and enabled to start at boot.
  service: name=td-agent state=started enabled=yes

- name: Create dicrectory for td-agent
  file:
    path: /etc/td-agent/conf.d
    owner: td-agent
    group: td-agent
    state: directory
